-- Supabase schema for workshop bookings.
-- Run this in the Supabase SQL editor.

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone_number text not null,
  vehicle_type text not null,
  service_type text not null,
  preferred_date date not null,
  preferred_time time not null,
  notes text,
  status text not null default 'pending',
  source text not null default 'landing_page',
  estimated_amount numeric(12, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bookings_status_check check (status in ('pending', 'in-progress', 'completed'))
);

create index if not exists bookings_created_at_idx on public.bookings (created_at desc);

alter table public.bookings enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'bookings'
      and policyname = 'Allow public insert bookings'
  ) then
    create policy "Allow public insert bookings"
      on public.bookings
      for insert
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'bookings'
      and policyname = 'Allow booking read access'
  ) then
    create policy "Allow booking read access"
      on public.bookings
      for select
      using (true);
  end if;
end $$;