-- Supabase schema for landing page leads.
-- Run this in the Supabase SQL editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null,
  source text not null default 'landing_page',
  created_at timestamptz not null default now(),
  constraint leads_email_format check (email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$')
);

create unique index if not exists leads_email_unique_idx on public.leads (lower(email));

alter table public.leads enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'leads'
      and policyname = 'Allow public read leads'
  ) then
    create policy "Allow public read leads"
      on public.leads
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'leads'
      and policyname = 'Allow public insert leads'
  ) then
    create policy "Allow public insert leads"
      on public.leads
      for insert
      with check (true);
  end if;
end $$;